### ISSUE TITLE
Issue accessing all folders and files within folders

### ISSUE THREAD

**Issue by amtaylr1** [terminological/google-docs-mendeley#1]
I do not have access to all the folders in my Mendeley library. I have tried resyncing, logging-out and signing back in, restarting my browser and still only have limited access to my folders.

**Comment by juanferza** [comment]
I have the same problem. what can i do for resolve that?

**Comment by robchallen** [comment]
How many folders do you have? Is it, by any chance, nested sub-folders that you can't see?

**Comment by robchallen** [comment]
p.s. sorry I missed this being opened - for some reasons the notifications were switched off.

**Comment by juanferza** [comment]
Just one. no sub-folders.
![captura](https://user-images.githubusercontent.com/33806676/32993668-68867570-cd29-11e7-9c65-3b03c00acf26.JPG)

**Comment by robchallen** [comment]
Could you try add a folder into the library and resync? I think it will
only see things in folders in the library.

**Comment by juanferza** [comment]
Hi, I've done that a lot of times, doesn´t work.

**Comment by robchallen** [comment]
Well, I think I need more information to know exactly what is going wrong.

There is an issue syncing new folders.If you connected a Mendeley account with no folders in it to start with then the plugin won't see anything until the folder structure is re-synced. 

It seems this is not happening properly from the re-sync button on the sidebar. Re-syncing folder structure can also be done from the menu. Try the following:

1. Make sure you have at least one folder in your Mendeley library
2. Close the plug in side bar.
3. Select menu option: Add-ons -> Mendeley citation plugin -> Clear default folder
4. Select menu option: Add-ons -> Mendeley citation plugin -> Set default folder 

Hopefully this will now show the full list of folders.

@amtaylr1 I think this would probably fix your issue as well and it would be good to know if that is the case.

**Comment by juanferza** [comment]
It worked, thank you!

**Comment by robchallen** [comment]
This has now been properly fixed, but not yet released to live as it needs to go through docs add-ons testing.

**Comment by robchallen** [comment]
Now released to the web store
