### ISSUE TITLE
library content does not show

### ISSUE THREAD

**Issue by user3491** [terminological/google-docs-mendeley#8]
I am trying to insert citations using Mendeley but unfortunately the citation library does not show. I have signed in and updated my library but nothing is showing, urgent assistance will be appreciated.

**Comment by robchallen** [comment]
Does your library contain any folders. The plugin can only see articles in folders.
If you have articles in a folder and have already selected a folder in the sidebar try hit the sync button, then closing the sidebar and re-opening it.
Please let me know if that fixes it.

**Comment by user3491** [comment]
I'll try putting them in folders.
Thanks,
Sithembile

**Comment by robchallen** [comment]
Assume this worked as no further feedback. I'll close this issue.
